---

- name: start go-server
  become: yes
  service:
    name: go-server
    state: started

- name: stop go-server
  become: yes
  service:
    name: go-server
    state: stopped

- name: restart go-server
  become: yes
  service:
    name: go-server
    state: restarted
